<?php

use Illuminate\Database\Seeder;
use App\City;
use Carbon\Carbon;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            // Punjab
            ['name' => "Abdul Hakim", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ahmadpur East", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ahmadpur Lumma", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ahmadpur Sial", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ahmedabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Alipur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Alipur Chatha", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Arifwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Attock", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Baddomalhi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bagh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bahawalnagar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bahawalpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bai Pheru", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Basirpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Begowala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhakkar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhalwal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhawana", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhera", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhopalwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Burewala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chak Azam Sahu", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chak Jhumra", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chak Sarwar Shahid", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chakwal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chawinda", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chichawatni", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chiniot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chishtian Mandi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Choa Saidan Shah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chuhar Kana", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chunian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dajal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Darya Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Daska", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Daud Khel", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Daultala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dera Din Panah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dera Ghazi Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dhanote", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dhonkal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dijkot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dina", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dinga", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dipalpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dullewala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dunga Bunga", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dunyapur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Eminabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Faisalabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Faqirwali", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Faruka", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Fateh Jang", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Fatehpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Fazalpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ferozwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Fort Abbas", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Garh Maharaja", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ghakar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ghurgushti", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Gojra", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Gujar Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Gujranwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Gujrat", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hadali", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hafizabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Harnoli", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Harunabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hasan Abdal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hasilpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Haveli", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hazro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hujra Shah Muqim", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Isa Khel", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jahanian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jalalpur Bhattian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jalalpur Jattan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jalalpur Pirwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jalla Jeem", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jamke Chima", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jampur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jand", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jandanwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jandiala Sherkhan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jaranwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jatoi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jauharabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jhang", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jhawarian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jhelum", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kabirwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kahna Nau", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kahror Pakka", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kahuta", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kalabagh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kalaswala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kaleke", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kalur Kot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kamalia", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kamar Mashani", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kamir", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kamoke", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kamra", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kanganpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Karampur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Karor Lal Esan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kasur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khairpur Tamewali", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khanewal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khangah Dogran", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khangarh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khanpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kharian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khewra", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khundian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khurianwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khushab", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kot Abdul Malik", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kot Addu", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kot Mithan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kot Moman", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kot Radha Kishan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kot Samaba", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kotli Loharan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kundian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kunjah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Lahore", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Lalamusa", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Lalian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Liaqatabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Liaqatpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Lieah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Liliani", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Lodhran", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ludhewala Waraich", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mailsi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Makhdumpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Makhdumpur Rashid", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Malakwal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mamu Kanjan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mananwala Jodh Singh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mandi Bahauddin", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mandi Sadiq Ganj", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mangat", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mangla", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mankera", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mian Channun", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Miani", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mianwali", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Minchinabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mitha Tiwana", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Multan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Muridke", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Murree", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mustafabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Muzaffargarh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Nankana Sahib", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Narang", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Narowal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Noorpur Thal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Nowshera", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Nowshera Virkan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Okara", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pakpattan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pasrur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pattoki", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Phalia", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Phularwan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pind Dadan Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pindi Bhattian", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pindi Gheb", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pirmahal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Qadirabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Qadirpur Ran", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Qila Disar Singh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Qila Sobha Singh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Quaidabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rabwah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rahim Yar Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Raiwind", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Raja Jang", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rajanpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rasulnagar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rawalpindi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Renala Khurd", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rojhan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Saddar Gogera", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sadiqabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Safdarabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sahiwal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Samasatta", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sambrial", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sammundri", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sangala Hill", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sanjwal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sarai Alamgir", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sarai Sidhu", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sargodha", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shadiwal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shahkot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shahpur City", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shahpur Saddar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shakargarh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sharqpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shehr Sultan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shekhupura", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shujaabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sialkot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sillanwali", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sodhra", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sohawa", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sukheke", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Talagang", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tandlianwala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Taunsa", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Taxila", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tibba Sultanpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Toba Tek Singh", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tulamba", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Uch", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Vihari", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Wah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Warburton", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Wazirabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Yazman", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Zafarwal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Zahir Pir", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],

            // Sindh
            ['name' => "Adilpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Badah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Badin", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bagarji", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bakshshapur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bandhi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Berani", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhiria City", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhiria Road", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bhit Shah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bozdar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Bulri", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chak", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chambar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chohar Jamali", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Chor", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dadu", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Daharki", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Daro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Darya Khan Mari", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Daulatpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Daur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dhoronaro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Digri", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Diplo", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Dokri", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Faqirabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Gambat", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Garello", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Garhi Khairo", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Garhi Yasin", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Gharo", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ghauspur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ghotki", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Golarchi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Guddu", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Gulistan-E-Jauhar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hala", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hingorja", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Hyderabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Islamkot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jacobabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jam Nawaz Ali", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jam Sahib", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jati", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jhol", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Jhudo", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Johi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kadhan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kambar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kandhra", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kandiari", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kandiaro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Karachi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Karampur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kario Ghanwar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Karoondi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kashmor", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kazi Ahmad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Keti Bandar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khadro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khairpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khairpur Nathan Shah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khandh Kot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khanpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khipro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khoski", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khuhra", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Khyber", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kot Diji", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kot Ghulam Mohammad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kotri", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kumb", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Kunri", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Lakhi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Larkana", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Madeji", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Matiari", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Matli", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mehar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mehrabpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Miro Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mirpur Bathoro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mirpur Khas", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mirpur Mathelo", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mirpur Sakro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mirwah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Mithi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Moro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Nabisar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Nasarpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Nasirabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Naudero", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Naukot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Naushahro Firoz", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Nawabshah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Oderolal Station", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pacca Chang", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Padidan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pano Aqil", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Perumal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Phulji", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pirjo Goth", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Piryaloi", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Pithoro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Radhan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rajo Khanani", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ranipur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ratodero", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rohri", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Rustam", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Saeedabad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sakrand", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Samaro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sanghar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sann", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sarhari", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sehwan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Setharja", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shah Dipalli", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shahdadkot", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shahdadpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shahpur Chakar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shahpur Jahania", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Shikarpur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sinjhoro", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sita Road", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sobhodero", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sujawal", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Sukkur", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Talhar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tando Adam", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tando Allah Yar", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tando Bagho", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tando Ghulam Ali", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tando Jam", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tando Jan Mohammad", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tando Mitha Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tando Muhammad Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tangwani", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Thano Bula Khan", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Thari Mirwah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Tharushah", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Thatta", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ther I", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],
            ['name' => "Ther I Mohabat", 'country_id' => 1, 'status' => 1, 'created_at' => Carbon::now()],

        ];

        DB::statement( 'SET FOREIGN_KEY_CHECKS=0;' );
        City::truncate();
        City::insert($cities);
        DB::statement( 'SET FOREIGN_KEY_CHECKS=1;' );
    }
}
